// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eKvarovi.Api.Data;

#nullable disable

namespace eKvarovi.Api.Migrations
{
    [DbContext(typeof(KvaroviDbContext))]
    partial class KvaroviDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("eKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Technician"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reporter"
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachmentPurposeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentPurposeId");

                    b.HasIndex("FaultReportId");

                    b.HasIndex("InterventionId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AttachmentPurpose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsDocuments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AttachmentPurposes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowsDocuments = false,
                            IsActive = true,
                            Name = "Fotografija prije rada",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            AllowsDocuments = false,
                            IsActive = true,
                            Name = "Fotografija nakon rada",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            AllowsDocuments = true,
                            IsActive = true,
                            Name = "Dokument",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTechnician")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresDeadline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultPriorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Level = 1,
                            Name = "Nizak",
                            RequiresDeadline = false,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "Srednji",
                            RequiresDeadline = false,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Level = 3,
                            Name = "Visok",
                            RequiresDeadline = false,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Level = 4,
                            Name = "Kritičan",
                            RequiresDeadline = true,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FaultPriorityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaultTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReporterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deadline");

                    b.HasIndex("FaultPriorityId");

                    b.HasIndex("FaultStatusId");

                    b.HasIndex("FaultTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewedById");

                    b.ToTable("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsClosed = false,
                            Name = "Zaprimljeno",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsClosed = false,
                            Name = "Pregledano",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsClosed = false,
                            Name = "Dodijeljeno",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsClosed = false,
                            Name = "U radu",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsClosed = false,
                            Name = "Riješeno",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsClosed = true,
                            Name = "Zatvoreno",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FaultTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Elektrika",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Voda",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Grijanje",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Mreža",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Građevinski radovi",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Ostalo",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InterventionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterventionStatusId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("WorkAssignmentId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterventionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("InterventionId", "MaterialId")
                        .IsUnique();

                    b.ToTable("InterventionMaterials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InterventionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsFinal = false,
                            IsSuccessful = false,
                            Name = "Planirana",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsFinal = false,
                            IsSuccessful = false,
                            Name = "U tijeku",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsFinal = true,
                            IsSuccessful = true,
                            Name = "Završena",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsFinal = true,
                            IsSuccessful = false,
                            Name = "Neuspješna",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Upravna zgrada",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Škola",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Zdravstvena ustanova",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Skladište",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultUnitPrice")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaterialUnitId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MaterialUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "kom",
                            IsActive = true,
                            Name = "Komad",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "m",
                            IsActive = true,
                            Name = "Metar",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "l",
                            IsActive = true,
                            Name = "Litra",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "kg",
                            IsActive = true,
                            Name = "Kilogram",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "pak",
                            IsActive = true,
                            Name = "Paket",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReassignReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("FaultReportId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkAssignments_OneActivePerReport")
                        .HasFilter("IsActive = 1");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkAssignments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUserRole", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Attachment", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.AttachmentPurpose", "AttachmentPurpose")
                        .WithMany("Attachments")
                        .HasForeignKey("AttachmentPurposeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Attachments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("Attachments")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("eKvarovi.Shared.Models.Employee", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttachmentPurpose");

                    b.Navigation("FaultReport");

                    b.Navigation("Intervention");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Location", "Location")
                        .WithMany("Employees")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.FaultPriority", "FaultPriority")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultPriorityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eKvarovi.Shared.Models.FaultStatus", "FaultStatus")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.FaultType", "FaultType")
                        .WithMany("FaultReports")
                        .HasForeignKey("FaultTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eKvarovi.Shared.Models.Location", "Location")
                        .WithMany("FaultReports")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Employee", "Reporter")
                        .WithMany("ReportedFaults")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Employee", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FaultPriority");

                    b.Navigation("FaultStatus");

                    b.Navigation("FaultType");

                    b.Navigation("Location");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.InterventionStatus", "InterventionStatus")
                        .WithMany("Interventions")
                        .HasForeignKey("InterventionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.WorkAssignment", "WorkAssignment")
                        .WithMany("Interventions")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterventionStatus");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionMaterial", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Intervention", "Intervention")
                        .WithMany("Materials")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Material", "Material")
                        .WithMany("Interventions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Intervention");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.MaterialUnit", "MaterialUnit")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialUnit");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.HasOne("eKvarovi.Shared.Models.Employee", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eKvarovi.Shared.Models.FaultReport", "FaultReport")
                        .WithMany("Assignments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eKvarovi.Shared.Models.Employee", "Technician")
                        .WithMany("Assignments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("FaultReport");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.AttachmentPurpose", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ReportedFaults");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultPriority", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultReport", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultStatus", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.FaultType", b =>
                {
                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Intervention", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Materials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.InterventionStatus", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Location", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("FaultReports");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.Material", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.MaterialUnit", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("eKvarovi.Shared.Models.WorkAssignment", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
